services:
  app:
    image: blog-front-prod
    build:
      context: ./blog-client
      dockerfile: Dockerfile

  backend:
    image: blog-back-prod
    build:
      context: ./blog-server
      dockerfile: Dockerfile

  debug-helper:
    image: busybox

  nginx:
    image: nginx:1.29
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - app # wait for the frontend container to be started
      - backend
