GET http://localhost:3003/api/blogs

###
GET http://localhost:3003/api/blogs/5a422b3a1b54a676234d17f9



###
POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json

{
    "title": "Con gai va con trai deu thich tao",
    "author": "PFPITME",
    "url": "vPod101.com",
    "likes": 9224
}
