GET http://localhost:3003/api/blogs

###
GET http://localhost:3003/api/blogs/68df34d1603ee536fd2afab7

###
DELETE http://localhost:3003/api/blogs/68df34d1603ee536fd2afab7


###
POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json

{
    "title": "missing URL should not work2",
    "author": "PFPITME"
}
